environments:
  oblivion:
    values:
      - values.yaml
      - clusterName: oblivion
      - vipRange: 148.187.83.245-148.187.83.249
  ultron:
    values:
      - values.yaml
      - clusterName: ultron
      - vipRange: 148.187.83.240-148.187.83.244
  goblin:
    values:
      - values.yaml
      - clusterName: goblin
      - vipRange: 148.187.83.235-148.187.83.239
  mandarin:
    values:
      - values.yaml
      - clusterName: mandarin
      - vipRange: 148.187.83.230-148.187.83.234
  kingpin:
    values:
      - values.yaml
      - clusterName: kingpin
      - vipRange: 148.187.83.225-148.187.83.229
  ronan:
    values:
      - values.yaml
      - clusterName: ronan
      - vipRange: 148.187.83.220-148.187.83.224
  hela:
    values:
      - values.yaml
      - clusterName: hela
      - vipRange: 148.187.83.215-148.187.83.219
  thanos:
    values:
      - values.yaml
      - clusterName: thanos
      - vipRange: 148.187.83.210-148.187.83.214
  doom:
    values:
      - values.yaml
      - clusterName: doom
      - vipRange: 148.187.83.205-148.187.83.209
  loki:
    values:
      - values.yaml
      - clusterName: loki
      - vipRange: 148.187.83.200-148.187.83.204


repositories:
  - name: argo-helm
    url: https://argoproj.github.io/argo-helm

  - name: jetstack
    url: https://charts.jetstack.io

  - name: cert-manager-webhook-pdns
    url: https://zachomedia.github.io/cert-manager-webhook-pdns

  - name: twun
    url: https://helm.twun.io

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: metallb
    url: https://metallb.github.io/metallb
    
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: argo-cd
    namespace: argocd
    chart: argo-helm/argo-cd
    version: 5.13.8
    wait: true
    condition: argo-cd.enabled
    values: 
      - values-argocd.yaml.gotmpl

  - name: argo-cd-templates
    namespace: argocd
    chart: ./charts/argocd
    wait: true
    condition: argo-cd.enabled
    needs:
    - cert-manager/cert-manager
    values: 
      - charts/argocd/values.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.10.0
    wait: true
    condition: cert-manager.enabled
    values: 
      - values-cert-manager.yaml

  - name: cert-manager-templates
    namespace: cert-manager
    chart: ./charts/cert-manager
    wait: true
    condition: cert-manager.enabled
    needs: 
      - cert-manager/cert-manager
    values: 
      - charts/cert-manager/values.yaml.gotmpl

  - name: cert-manager-webhook-pdns
    namespace: cert-manager
    chart: cert-manager-webhook-pdns/cert-manager-webhook-pdns
    version: 2.1.3
    wait: true
    condition: cert-manager.enabled
    needs: 
      - cert-manager/cert-manager
    values: 
      - values-cert-manager.yaml

  - name: docker-registry
    namespace: docker-registry
    chart: twun/docker-registry
    version: 2.2.2
    wait: true
    condition: docker-registry.enabled
    values: 
      - values-docker-registry.yaml.gotmpl

  - name: docker-registry-templates
    namespace: docker-registry
    chart: ./charts/docker-registry
    wait: true
    condition: docker-registry.enabled
    needs: 
      - cert-manager/cert-manager
    values: 
      - charts/docker-registry/values.yaml.gotmpl

  - name: external-dns
    namespace: external-dns
    chart: bitnami/external-dns
    version: 6.11.3
    wait: true
    condition: external-dns.enabled
    values: 
      - values-external-dns.yaml.gotmpl

  - name: external-dns-templates
    namespace: external-dns
    chart: ./charts/external-dns
    wait: true
    condition: external-dns.enabled
    values: 
      - charts/external-dns/values.yaml.gotmpl
    
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.4.0
    wait: true
    condition: ingress-nginx.enabled
    needs: 
      - metallb-system/metallb
    values:
      - values-ingress-nginx.yaml

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.13.7
    wait: true
    condition: metallb.enabled
    
  - name: metallb-templates
    namespace: metallb-system
    chart: ./charts/metallb
    wait: true
    condition: metallb.enabled
    needs: 
      - metallb-system/metallb
    values: 
      - charts/metallb/values.yaml.gotmpl

  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.22.1
    wait: true
    condition: vault.enabled
    values: 
      - values-vault.yaml.gotmpl

  - name: vault-templates
    namespace: vault
    chart: ./charts/vault
    wait: true
    condition: vault.enabled
    needs: 
      - cert-manager/cert-manager
    values: 
      - charts/vault/values.yaml.gotmpl

