apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
spec:
  secretName: argocd-tls
  commonName: argocd.{{ .Values.clusterName }}.hack2022.ch
  dnsNames:
  - argocd.{{ .Values.clusterName }}.hack2022.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt