apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: linuxkit/sshd:7e71b29a4223436c741d73149f880f7bf5d44dd7
        ports:
        - containerPort: 22

---

apiVersion: v1
kind: Service
metadata:
  name: sshd
spec:
  selector:
    app: sshd 
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22