apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo
spec:
  secretName: echo
  commonName: echo.test.hack2022.ch
  dnsNames:
  - echo.test.hack2022.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt