apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  secretName: docker-registry-tls
  commonName: registry.test.hack2022.ch
  dnsNames:
  - registry.test.hack2022.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt