apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-tls
  commonName: argocd.test.hack2022.ch
  dnsNames:
  - argocd.test.hack2022.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt