apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
  namespace: harbor
spec:
  secretName: harbor-tls
  commonName: harbor.test.eoggian.tk
  dnsNames:
  - harbor.test.eoggian.tk
  - notary.test.eoggian.tk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt