apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  secretName: vault-tls
  commonName: vault.test.hack2022.ch
  dnsNames:
  - vault.test.hack2022.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt