apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  secretName: vault-tls
  commonName: vault.test.eoggian.tk
  dnsNames:
  - vault.test.eoggian.tk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt