---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: eoggian@cscs.ch
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-pdns-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.zacharyseguin.ca
          solverName: pdns
          config:
            host: http://ns1.hack2022.ch:8081
            apiKeySecretRef:
              name: pdns-secret
              key: pdns_api_key
              # Optional config, shown with default values
              #   all times in seconds
            ttl: 120
            timeout: 30
            propagationTimeout: 120
            pollingInterval: 2
